version: '3'
services:
  soap-db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    volumes:
      - ./script/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=scholee_soap
      - MYSQL_USER=scholee
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  soap-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: soap-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - soap-db
